apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-app
  template:
    metadata:
      labels:
        app: credit-app
    spec:
      containers:
      - name: credit-app
        image: 698subhashchandra/credit-ratingapis:latest
        ports:
        - containerPort: 80