apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-rating-api-deployment
  namespace: credit-rating-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-rating-api
  template:
    metadata:
      labels:
        app: credit-rating-api
    spec:
      containers:
      - name: credit-rating-api-container
        image: 698subhashchandra/credit-ratingapis:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi