apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-rating-api-deployment
  namespace: credit-rating-api
  labels:
    app: credit-rating-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-rating-api
  template:
    metadata:
      labels:
        app: credit-rating-api
    spec:
      containers:
        - name: credit-rating-api-container
          image: 698subhashchandra/credit-ratingapis:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
