apiVersion: v1
kind: Pod
metadata:
  name: credit-rating-api
  namespace: credit-rating-api

spec:
  containers:
    - name: credit-rating-api-container
      image: 698subhashchandra/credit-ratingapis:latest
      ports:
        - containerPort: 8000