apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-app-replica-set
  namespace: credit-rating-api
  labels:
    app: guestbook
    tier: node-label
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: node-label
  template:
    metadata:
      namespace: credit-rating-api
      labels:
        tier: node-label
    spec:
      containers:
      - name: credit-rating-api-container-rep
        image: 698subhashchandra/credit-ratingapis:latest