#apiVersion: v1
#kind: Service
#metadata:
#  name: credit-rating-api-service
#  namespace: credit-rating-api
#spec:
#  type: NodePort
#  selector:
#    app: credit-rating-api
#  ports:
#    - port: 80
#      targetPort: 8000
#      nodePort: 30003

apiVersion: v1
kind: Service
metadata:
  name: credit-rating-api-service
  namespace: credit-rating-api
spec:
  type: NodePort
  selector:
    app: credit-rating-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30003
